# Generated by Django 5.1.3 on 2025-03-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_app", "0003_category_user_alter_rating_user_alter_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_image",
            field=models.ImageField(null=True, upload_to="category_image/"),
        ),
    ]
