# Generated by Django 5.1.3 on 2025-03-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_app", "0004_category_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(blank=True, null=True, upload_to="category_image/"),
        ),
    ]
