# Generated by Django 5.1.3 on 2025-03-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_app", "0003_category_user_alter_rating_user_alter_review_user"),
        ("user_app", "0002_buyerprofile_farmerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerprofile",
            name="categories",
            field=models.ManyToManyField(to="product_app.category"),
        ),
    ]
