# Generated by Django 5.1.3 on 2025-02-14 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={
                "ordering": ["-default"],
                "verbose_name_plural": "Shipping Addresses",
            },
        ),
    ]
